config/routes.rb
Rails.application.routes.draw do
  resources :greetings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "greetings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/greeting.rb
class Greeting < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[ show edit update destroy ]

  # GET /greetings or /greetings.json
  def index
    @greetings = Greeting.all.order(created_at: :desc)
  end

  # GET /greetings/1 or /greetings/1.json
  def show
  end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit
  end

  # POST /greetings or /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to root_url, notice: "Greeting was successfully created." }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greetings/1 or /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to greeting_url(@greeting), notice: "Greeting was successfully updated." }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1 or /greetings/1.json
  def destroy
    @greeting.destroy

    respond_to do |format|
      format.html { redirect_to greetings_url, notice: "Greeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_greeting
    @greeting = Greeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def greeting_params
    params.require(:greeting).permit(:name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
  def gravatarized_url(name)
    hash = Digest::MD5.hexdigest(name)
    "https://www.gravatar.com/avatar/#{hash}?d=wavatar"
  end
end

app/views/greetings/_form.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Send me a message!</h5>
    <%= bootstrap_form_with(model: greeting) do |form| %>
      <%= form.alert_message "Please fix the errors below.", error_summary: false %>
      <%= form.text_field :name %>
      <%= form.text_area :message %>
      <%= form.primary class: 'btn btn-outline-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/greetings/_greeting.html.erb
<div class='media' id="<%= dom_id greeting %>">
  <%= image_tag gravatarized_url(greeting.name), class: 'align-self-start mr-3' %>
  <div class="media-body">
    <h5 class="mt-0"><%= greeting.name %></h5>
    <%= greeting.message %>
  </div>
</div>

app/views/greetings/edit.html.erb
<h1>Editing greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Show this greeting", @greeting %> |
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/index.html.erb
<p style="color: green"><%= notice %></p>
<%= render 'greetings/form', greeting: Greeting.new %>
<div class='mt-3' id="greetings">
  <%= render @greetings %>
</div>

app/views/greetings/new.html.erb
<h1>New greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @greeting %>

<div>
  <%= link_to "Edit this greeting", edit_greeting_path(@greeting) %> |
  <%= link_to "Back to greetings", greetings_path %>

  <%= button_to "Destroy this greeting", @greeting, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guesto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <main role='main' class="container">
      <%= yield %>
    </main>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">Guest Book by 
          <a class='text-decoration-none' target='_blank' href="https://github.com/blessed-sibanda">Blessed Sibanda</a>
        </span>
      </div>
    </footer>
  </body>
</html>